### ISSUE TITLE
Some GPIO pins not available: Why?

### ISSUE THREAD

**Issue by friebel** [LuxuSam/PhysicalButton#30]
Hello Sam,

Thank you for the plugin! When seeing it announced, I immediately designed and printed a button housing. So much fun :)

I'm a bit surprised that not all GPIO pins are available. For example, I don't see 14, 15, and 19. Code search didn't reveal a list, so it's likely not hardcoded? Do you have any idea why above pins are missing from the list? My current setup happens to use pin 19 and it works from a Python script.

```
#!/usr/bin/env python
from gpiozero import Button
from time import sleep

button_pins = (
    2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
    14, 15,  # not in PhysicalButton list
    16, 17, 18,
    19,  # not in PhysicalButton list
    20, 21, 22, 23, 24, 25, 26, 27,
)

buttons = [(pin, Button(pin)) for pin in button_pins]

while True:
    pressed = []
    for pin, button in buttons:
        if button.is_pressed:
            pressed.append(pin)
    if pressed:
        print(pressed)
    sleep(.1)
```

Thank you!
Thomas

**Comment by LuxuSam** [comment]
Hi,

The available GPIO pins are hardcoded in _octoprint_physicalbutton/static/js/physicalbutton.js_ (line 15-17).
I did not add those pins to the list as they seem to provide special behavior (see [GPIO14](https://pinout.xyz/pinout/pin8_gpio14), [GPIO15](https://pinout.xyz/pinout/pin10_gpio15), [GPIO19](https://pinout.xyz/pinout/pin35_gpio19))

Cheers,
Sam
