### ISSUE TITLE
[FEATURE] Start/Cancel toggle action

### ISSUE THREAD

**Issue by calebmah** [LuxuSam/PhysicalButton#34]
**Describe the solution you'd like**
It would be awesome if there were a Start/Cancel toggle action just like the recently added pause toggle action! That would allow starting a print (if nothing is printing) and cancelling an ongoing print with the same button! 

**Additional context**
Thanks again for the quick turnarounds and releases!

**Comment by LuxuSam** [comment]
Hi,

Thanks for the request.
Do you mean like start the last selected file? Like the usual start action, but with the addition if you are already printing that the print is canceled?

Cheers,
Sam

**Comment by LuxuSam** [comment]
I finished programming the new action, it will be added in the next release.
