### ISSUE TITLE
 [BUG] 'Physical-Button' requires a different Python: 2.7.16 not in '>=3, <4'

### ISSUE THREAD

**Issue by Guid-o-nator** [LuxuSam/PhysicalButton#39]
**Plugin Version**
unknown, currently available under https://github.com/LuxuSam/PhysicalButton/archive/master.zip

**Describe the bug**
- Cannot find PlugIn when searching in Plugin Manager
- Cannot install, wrong Python version:
- ERROR: Package 'Physical-Button' requires a different Python: 2.7.16 not in '>=3, <4'

**To Reproduce**
OctoPrint 1.6.1 - Python 2.7.16 - OctoPi 0.17.0

**Expected behavior**
- Find Plugin in Plugin Manager
- Install Plugin

**Comment by LuxuSam** [comment]
Hi,

Thanks for the bug report, but there is nothing I can do about that.
I made the plugin support only Python 3. You seem to have Python 2 installed.
If you want to update Python on your raspberry pi, you can read through this [Upgrade your OctoPrint install to Python 3!](https://octoprint.org/blog/2020/09/10/upgrade-to-py3/)

Cheers,
Sam

**Comment by rnsi** [comment]
I get the same error. I have python 2 and 3 installed, but system info shows "env.python.version: 2.7.16". Running OctoPrint 1.6.1. Maybe instead of calling python we need to call python3?

**Comment by LuxuSam** [comment]
What is the output of `pip --version` and `python --version` on your pi?

**Comment by LuxuSam** [comment]
You need to have Python 3 set as standard as I cannot influence how the plugin is installed 😅

**Comment by rnsi** [comment]
Older versions of OctoPi used Python2 as the default. Use the script here: https://octoprint.org/blog/2020/09/10/upgrade-to-py3/ to upgrade the OctoPi installation and this plug-in will install. This *may* break old plug-ins that are Python2 only.

Setting the OS default Python version is not enough. You need to change OctoPi.

**Comment by LuxuSam** [comment]
Okay, I wasn't completely sure about that. But I also posted that link already above :)

Cheers,
Sam
