### ISSUE TITLE
[FEATURE] Support for Keypad Matrix

### ISSUE THREAD

**Issue by electronicm** [LuxuSam/PhysicalButton#44]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
With such a keypad, you could put various functions on physical keys, but without taking up too many GPIOs and space.

**Additional context**
[![KeyPad at Reichelt.de](https://cdn-reichelt.de/resize_70x70/web/artikel_ws/A300/SENSOREN-SET7-01.jpg)](https://www.reichelt.de/entwicklerboards-button-matrix-16-taster-debo-button-mtx-p192141.html) [![Keypad at SparkFun.com](https://cdn.sparkfun.com/r/92-92/assets/parts/5/9/3/ButtonPad-05-L.jpg)](https://learn.sparkfun.com/tutorials/button-pad-hookup-guide)
https://projects-raspberry.com/raspberry-pi-with-a-keypad-matrix/

_BTW: If you do something right once, you have the work forever. :D_

**Comment by LuxuSam** [comment]
Hi, thank you for the feature request!

Sadly, I don't think I want to include that in this plugin, I would have to change to much of the button control logic to support a keyboard matrix 😅
I think it would make sense to create a new plugin for this purpose!

Cheers,
Sam
