### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by pasalino** [LuxuSam/PhysicalButton#54]
After installation i can't see the plugin in my plugin list.

Physical Button (0.5.0)
OctoPrint 1.7.3 
Python 3.7.3 
OctoPi 0.18.0

**Comment by LuxuSam** [comment]
Hi,
Could you please attach the `octoprint.log` file? You can download it in the settings under OctoPrint/Logging by clicking on the download button on the right side of the file.

**Comment by pasalino** [comment]
[octoprint 2.log](https://github.com/LuxuSam/PhysicalButton/files/8018735/octoprint.2.log)

**Comment by LuxuSam** [comment]
I see in your log that the plugin was installed but is disabled. But I can also see that OctoPrint is not restarting after the installation. 

 ```
2022-02-07 18:37:33,807 - octoprint.plugins.pluginmanager - INFO - The plugin was installed successfully: Physical Button, version 0.5.0
2022-02-07 18:39:34,733 - octoprint.server.api.system - INFO - Performing command for core:restart: sudo service octoprint restart
2022-02-07 18:39:34,807 - octoprint.server.api.system - WARNING - Command for core:restart failed with return code 1:
! STDOUT: 
! STDERR: sudo: no tty present and no askpass program specified
```

That error pops up multiple times in the log file.

**Comment by LuxuSam** [comment]
Are you running OctoPrint on a Raspberry Pi?
If you are not running OctoPrint on a Raspberry Pi, then you cannot use my plugin as this is not supported.
 
Did you change your restart commands in your settings under OctoPrint/Server?
The restart OctoPrint command should look like this: `sudo service octoprint restart`.
