### ISSUE TITLE
Button action on Raspi startup

### ISSUE THREAD

**Issue by seppelicous** [LuxuSam/PhysicalButton#62]
**Plugin Version**
0.5.0

**Question**
I use GPIO17 to send an action. The button is connected to ground and it works as intended.
Problem is on raspy startup. I am not an Raspberry expert, but on on start the GPIO17 pin is low and that seems to activate the action once. How can I prevent this behaviour? Do I have to use an pul up resistor or a different pin to get rid of this?

My pins 1-8 are already in use, so I cannot use pins that are HIGH on startup.

Thank you!

**Comment by LuxuSam** [comment]
Hi,

That is really strange and I cannot think of a reason why this should be happening. 
You should not have to use a pull-up as I set those internally. You could try another pin, but as already said this should not happen. Do you have it set up as "Normally Open" or "Normally Closed"?

I could have a look at your octoprint.log to see if I get a clue from there.  
For this go to the logging tab in your settings and add octoprint.plugins.physicalbutton with debug level selected.

Cheers,
Sam

**Comment by seppelicous** [comment]
Thank you for your fast reply. It is "Normaly open". I changed the GPIO twice and now cannot reproduce it anymore. That's weird. Now, since was another issue, I will close this.
