### ISSUE TITLE
[FEATURE] Prevent button execution while printing

### ISSUE THREAD

**Issue by wdonders** [LuxuSam/PhysicalButton#67]
Great work on this awesome plugin, thank you!

However, I've built this great new 3D-printer but I have trouble with (probably) EFI interference.
Every ones in a while, a button is triggered during a print without any obvious reason.
This caused some troubles; Once the button "shutdown Pi" was triggered, shutting the whole system down during printing.
An other time, the "cool down" button was triggered, causing the hot end to block up and the extruder grinded happily for hours when discovered something was wrong.
I've tried to increase the duration you have top press a button, but that does not seem to help a lot.

Request:
An option you can enable to prevent execution a button while printing.
Preferably per button; You don't want a "cool down" button to be executed during print, however, a "LED strip on" button is not a problem.

This would be a big help, because for now, I had to disable all my buttons except the LED strip button..
I've tried to solve the problem hardware wise, but cannot seem to solve this issue completely..

**Comment by LuxuSam** [comment]
Hi,

Thank you for that suggestion, that is a really good idea!
I'll add it as soon as I have time to work on the plugin again (I have a pretty stressful semester at the moment).

Cheers,
Sam

**Comment by wdonders** [comment]
Thank LuxuSam, that would be so great!!
I can only imaging that EFI interference could be a source of trouble for more printer builders..

**Comment by LuxuSam** [comment]
I had a similar problem one where my buttons triggered when I plugged something in the power strip which also runs the printer and rpi.

**Comment by LuxuSam** [comment]
I added a feature branch with the proposed changes, if you are interested in trying them out do as following:

If you do not know how to install it with a link do as following:

1. Open Settings
2. Go to Plugin Manager
3. Click +Get More
4. Paste `https://github.com/LuxuSam/PhysicalButton/archive/refs/heads/feature-additional-button-options.zip` under ... from URL
5. Hit Install next to that text field

**Comment by wdonders** [comment]
Wow, nice work! I will have to find some time next week to test it. 👍

**Comment by wdonders** [comment]
I Couldn't wait to try 😊
Seems to work great! Hope this will prevent my printer from crashing due to a false button trigger during printing. Time will tell..
Thank you so much!

**Comment by wdonders** [comment]
All worked fine, until i upgraded Octoprint to version 1.8.1
Now, i get random triggers every now and then :-(
The 'Enabled while printing' checkbox is unchecked for all buttons.
Did something change in the way Octoprint tells it's busy printing in this new version or something?
Weird..

**Comment by LuxuSam** [comment]
Did you download the release I did a couple of days ago?

**Comment by wdonders** [comment]
I first installed the version you had ready on june 18th (see your post above).
After that I installed your official 0.6.0 version when it was released (with backup and restore functionality, nice!)
Should I try to completely uninstall and reinstall 0.6.0?

**Comment by LuxuSam** [comment]
Could you download the config with the new backup feature and the octoprint.log file and attach those here? 
Then I can have a look and try to figure out what's happening :)

**Comment by LuxuSam** [comment]
I just thought of simething I forgot to mention. You have to enable debug logging in octoprint for this plugin

**Comment by LuxuSam** [comment]
I think I have found the bug.
I changed something last minute before the release where I forgot to flip a negation 😅 
I changed from `not is_ready` to `not is_printing` instead of simply `is_printing`.  Using `not is_ready`, would have prevented the buttons from working when the printer is not connected while having 'enabled while printing' unchecked.

Can you try out this fix? You can install it the same way as mentioned above :)
`https://github.com/LuxuSam/PhysicalButton/archive/refs/heads/bug-enabled-while-printing.zip`

**Comment by LuxuSam** [comment]
I think that it is a pure coincidence that only the lights button triggered.

**Comment by wdonders** [comment]
Nice, to know that it is probably solved :-)
I've installed the new version and will report soon when I have a chance to test it.

**Comment by LuxuSam** [comment]
Did you have time to test it yet? :)

**Comment by wdonders** [comment]
Sorry I did not report back, it seems to work great now! 😎
