### ISSUE TITLE
[FEATURE] Add more actions

### ISSUE THREAD

**Issue by DarkStiller** [LuxuSam/PhysicalButton#73]
Maybe it help some people, when you add some more actions by default. Somthing like Preheat Hotend; Preheat Bed; Preheat both; simple switching the GIO-pin, when the user has there a relais for a lamp or somthing like that connected - such essential things. So user be able to make everything with your plugin and need no other plugin for other functions.

**Comment by LuxuSam** [comment]
Hi,

Thank you for the feature request.
Sorry but I don't think I'll add actions like those.
Temperatures can already be set with the Gcode activity (M104/M109 and M140/M190) and relais could be triggered with the output activity.

Cheers,
Sam
