### ISSUE TITLE
 [BUG] OctoPrint enters Safe Mode after enabling Physical Button plugin (only for the first time)

### ISSUE THREAD

**Issue by Defozo** [LuxuSam/PhysicalButton#76]
**Plugin Version**
0.6.1

**Describe the bug**
After enabling the plugin, my OctoPrint instance restarts and enters Safe Mode. However, after the next restart, everything goes back to normal and the plugin works correctly.

**Expected behavior**
After enabling the Physical Button plugin and restarting OctoPrint, the instance should start normally and allow the user to control the printer using physical buttons connected to the Raspberry Pi without needing an additional restart.

**Screenshots / Logs**
There are no apparent issues or errors in my octoprint.log.

**Additional context**
I'm using OctoPrint 1.8.7 on a Raspberry Pi 4 Model B Rev 1.5, and my printer is a Prusa Mini+. The detected firmware is Prusa-Firmware-Buddy 4.4.1-RC2+4193 (Github).

**Comment by LuxuSam** [comment]
Hi,
Thank you for your bug report. 
Can you add physical button debugging in the logging tab for your octoprint instance and try to recreate the behavior? 
Without an octoprint.log file, I can't do much as I'm not able to reproduce that :)

Cheers,
Sam
