### ISSUE TITLE
[FEATURE] Short and Long press functions for ONE physical button

### ISSUE THREAD

**Issue by princeje** [LuxuSam/PhysicalButton#78]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to have one button on my printer that can perform an action on a short press & also perform a different function when held for X number of seconds.

**Additional context**
I had a python script that did this but it did not work well with octoprint. My script would just record the seconds the pin was pulled up and decide what to do from there.

**Comment by LuxuSam** [comment]
Hi, thank you for the feature request! There is already a similar one open (see #32).
I'm currently working on my master thesis and will (finally) to look into that feature when I'm done :) 
I created a concept already on how I imagine to implement it, but did not have any time yet.

Cheers,
Sam
