### ISSUE TITLE
[QUESTION] How to setup keyboard hot keys 

### ISSUE THREAD

**Issue by FlufMastaFlex** [LuxuSam/PhysicalButton#83]
Rookie coder here, I know enough to fumble through the basics, so bare with me as I try to get my idea across.

I have multiple Raspberry Pis setup with OctoPrint and OctoDash with their own printers, but only one touch screen that I would like to use to control them for convenience and cost efficiency. What I would like to do is setup buttons programmed to type one the IP address for each of the printers when pressed from a keyboard input to the section asking for the IP address in OctoDash. That way I could switch between printers being controlled without needing to have a key board/pad connected to the touch screen Pi. I know enough to do system command such as "sudo -reboot", or something else similar. But I am not sure house to run.

So, it might just be a lack of coding knowledge, but how could I use this plug-in to type out my specified IP addresses as hot keys into OctoDash?

Thanks for any help in advance,

FlufMastaFlex

**Comment by LuxuSam** [comment]
Hi,

I'm not sure this can be achieved purely with thie PhysicalButton plugin.
I do not use OctoDash and do not have experience with it.
If it can be achieved by a system command/shell script, you could ask at OctoDash how to do it!

Cheers,
Sam
