### ISSUE TITLE
Cannot Install - "Install Unknown"

### ISSUE THREAD

**Issue by antonyburden** [LuxuSam/PhysicalButton#85]
**Plugin Version**
0.6.1

**Describe the bug**
After install and prior to restart - this message appears "Install Unknown:"

Python 3.7.3
OctoPi 0.17.0

The plugin does not show up within OctoPrint

**Comment by LuxuSam** [comment]
Hi,

Could you add your octoprint.log file? Without that file, I cannot help you.

Cheers,
Sam

**Comment by LuxuSam** [comment]
This bug could also be related to issue #82. Please check if my proposed solution there works for you.

**Comment by antonyburden** [comment]
Thanks, your new install URL has worked. I've attached it anyway:
[octoprint.log](https://github.com/LuxuSam/PhysicalButton/files/13328422/octoprint.log)

**Comment by LuxuSam** [comment]
Thanks! 
Yes, it is the exact same problem as in the other issue. I'll wait until I get some more feedback there before I publish an official release. When I update, you should receive a notification in the OctoPrint interface, and you can install it from there as usual.

I'll close this issue!
